CLI.md
holepunchto/pear-docs pull request #1
Opened 2023-11-28 05:40 UTC by paragmore

2023-11-30 11:01 UTC, davidmarkclements commented on cli.md
> +The Pear Command Line Interface (CLI) is the entry point for developers. It provides access to development, deployment and production capabilities.
```suggestion
The Pear Command Line Interface (CLI) is a developer tool for making and sharing Pear applications.
```

2023-11-30 11:08 UTC, davidmarkclements commented on cli.md
> +The files are loaded from disk instead of Hypercores. Which means the changes made would only be present in local environment and won't be added to P2P storage.
iterate this, it's indicating that files are auto-added to p2p storage and that is not how it works. It's also suggesting that P2P storage may not be on disk, also not true. 

Something like:

In development mode applications are loaded from the filesystem while production Pear applications load from P2P storage structures

2023-11-30 11:10 UTC, davidmarkclements commented on cli.md
> +On running, CLI outputs diff information from previous version and project key.
the CLI - make sure same everywhere

2023-11-30 11:10 UTC, davidmarkclements commented on cli.md
> +Seeding in Pear refers to the process of initializing or updating a Pear project with data from other Hypercores or channels.
initializing is very confusing language to use here

iterate this

2023-11-30 11:11 UTC, davidmarkclements commented on cli.md
> +| --checkout=n \| release \| staged | Launches a specific version of the application. You can specify a version (n), or use keywords like release or staged to launch the latest release or staged vers
never ever use "you"

this is passive voice, not active voice

2023-11-30 11:12 UTC, davidmarkclements commented on cli.md
> +This command provides details about the specified key, offering insights into the associated Pear project or application, including its name, channel, and release version.
what does the key represent? what are getting info about? the application.

2023-11-30 11:13 UTC, davidmarkclements commented on cli.md
> +#### `pear stage <channel|key> [dir]`
this is not advanced command. Please tell me if we say this is advanced in any of the help. It is not advanced.

2023-11-30 11:14 UTC, davidmarkclements commented on cli.md
> +#### `pear stage <channel|key> [dir]`
oh this looks misplaced actually, need to put the actual advanced commands in here and remove this boilerplate

2023-11-30 11:14 UTC, davidmarkclements requested changes
iterate

2023-12-01 17:58 UTC, davidmarkclements commented on cli.md
> +A Pear project **must** have a `package.json` file and an entry file (`index.html`). The pear init command helps generate these files.
```suggestion
A Pear project **must** have a `package.json` file and an entry file (`index.html`). The `pear init` command helps generate these files.
```

make sure any inline-commands are properly denoted elsewhere

2023-12-01 18:02 UTC, davidmarkclements commented on cli.md
> +In development mode, applications load from the filesystem, which is handy for easy testing and tweaking. While production Pear applications load from P2P storage structures
"handy for easy testing and tweaking" is noise. eliminate noise
also the grammar here is off, starting a sentence with While and then drops off a cliff 

this needs to be iterated again

2023-12-01 18:03 UTC, davidmarkclements commented on cli.md
> +The channel name must be specified when running stage command for first time, in order to generate the initial key.
```suggestion
The channel name must be specified when running stage command for the first time, in order to generate the initial key.
```

2023-12-01 18:05 UTC, davidmarkclements commented on cli.md
> +On running, the CLI outputs diff information from previous version and project key.
confusing, - could just say "from previous version" but it could def be made clearer than that

2023-12-01 18:06 UTC, davidmarkclements commented on cli.md
> +Launch an application from Hyperspace using its key id.
avoid introducing new terms. No where have we said `id` before. 

this needs more explaining, Hyperspace is dead, don't use that phrase

2023-12-01 18:07 UTC, davidmarkclements commented on cli.md
> +Command adds a release tag for a given version (release length) to the Hypercores with the specified channel or key.
contextually we know that commands are being described, so it does not need to start with "Command adds"

2023-12-01 18:12 UTC, davidmarkclements commented on cli.md
> +Command adds a release tag for a given version (release length) to the Hypercores with the specified channel or key.
also we should be supplemnting and explaining information in from the help output. There's information that's now missing. 

Instead of "Hypercores" ->  "Pear Project"

2023-12-01 18:16 UTC, davidmarkclements commented on cli.md
> +These advanced commands are for power-users helpful for internal development, and platform debugging.
```suggestion
These advanced commands here for internal development, platform debugging and power users.
```

2023-12-01 18:38 UTC, davidmarkclements commented on cli.md
> +The Sidecar is a local-running process that provides access to P2P functionality.
```suggestion
When any Pear command is executed, it first starts and or connects to the Pear Sidecar. The Pear Sidecar is a local-running HTTP and IPC server which provides access to the P2P data-structures (Hypercores) that contain Pear Applications. 

The `pear sidecar` command sends a shutdown signal to Pear Sidecar, and then the command client process itself becomes the new Sidecar so that any output from the Sidecar is reflected directly in the terminal.
```

2023-12-01 18:42 UTC, davidmarkclements commented on cli.md
> +Open a Read-Evaluate-Print-Loop (REPL) session with the Sidecar. A key is printed out during the Pear REPL session, which can be used with the REPL-swarm module to establish a connection.
what does that mean?  what is a REPL?

don't bring up repl-swarm etc (also side note - it would be `repl-swarm` not REPL-swarm) 

keep it generic: it prints a command that you can run to open the session

2023-12-01 18:43 UTC, davidmarkclements commented on cli.md
> +Outputs Pear version and versions of top level dependencies used.
```suggestion
Outputs versions of Pear and its dependencies.
```

avoid repetition if you can

2023-12-01 18:44 UTC, davidmarkclements commented on cli.md
> +Outputs Pear version and versions of top level dependencies used.
actually put `pear versions` in advanced `pear -v` is for general usage

2023-12-01 18:46 UTC, davidmarkclements commented on cli.md
> +Used to synchronize files from a specified key to a specified directory.
```suggestion
Synchronize files from a specified key to a specified directory.
```
avoid "Used to"

2023-12-01 18:48 UTC, davidmarkclements commented on cli.md
> +This command is useful for extracting or backing up data from a Pear project's Hypercore to a local directory.
```suggestion
The `pear dump` command can remotely extract data from a Pear Project to a local directory.
```

avoid "This command is useful", 
avoid "synonym or synonym" 

try to highlight "remote" when possible

2023-12-01 19:01 UTC, davidmarkclements commented on cli.md
> +The Sidecar is a local-running process that provides access to P2P functionality.
this is the probably the only place in the CLI docs that we should mention Hypercores. Every where else its a Pear Project / Pear Application or P2P data-structure depending on context.

2023-12-01 19:01 UTC, davidmarkclements commented on cli.md
> +
```suggestion
```

2023-12-01 19:01 UTC, davidmarkclements commented on cli.md
> +and then becomes the Sidecar.
```suggestion

```

2023-12-01 19:02 UTC, davidmarkclements commented on cli.md
> +This command instructs any existing Sidecar process to shutdown
```suggestion
```

2023-12-01 19:02 UTC, davidmarkclements commented on cli.md
> +| --mem            | Memory mode: RAM corestore. Sidecar should run in memory mode, utilizing RAM for corestore operations. Useful for testing or running a Pear application with an in-memory storage
should? make this less wordy

2023-12-01 19:03 UTC, davidmarkclements commented on cli.md
> +Get metadata for a application from its key.
an.

lookup

BY key

2023-12-01 19:04 UTC, davidmarkclements commented on cli.md
> +This command provides details about the application from specified key, offering insights into the associated Pear project or application, including its name, channel, and release version.
Pear Project

avoid "This command" (only leave in one in pear sidecar)

2023-12-01 19:05 UTC, davidmarkclements commented on cli.md
> +| --store \| -s=path                | Sets the path for the Application Storage. This allows user to specify where the application will store its data.
this is saying the same thing twice. 

make sure nothing is saying the same thing twice in a different way.

2023-12-01 19:12 UTC, davidmarkclements commented on cli.md
> +| --tmp-store \| -t                 | Automatically uses a new temporary folder as the store path. This is useful for temporary or disposable storage during testing.
syn or syn

2023-12-04 10:08 UTC, davidmarkclements commented on cli.md
> +| --no-watch         | Disables watch-reload. In development mode, watch-reload is a feature that automatically reloads the application when changes are detected. |
```suggestion
| --no-watch         | Disables watch-reload. In development mode, watch-reload is a feature that automatically reloads application file when changes are detected. |
```

2023-12-04 10:09 UTC, davidmarkclements commented on cli.md
> +For reseeding, specify a public key (or punch link) of a project.
punch link is not a thing - remove this everywehre

2023-12-04 10:09 UTC, davidmarkclements commented on cli.md
> +The `pear dump` command can `remotely` extract data from a Pear Project to a local directory.
why is remotely in a code style? it's a word not a library?

2023-12-04 10:12 UTC, davidmarkclements commented on cli.md
> +On running, the CLI outputs difference information between the current and previous version, along with the project key..
why two dots

"outputs difference information" is obtuse, try searching for that term nothing relevant comes up 

"outputs the difference"

2023-12-04 10:18 UTC, davidmarkclements commented on cli.md
> +| --checkout=n \| release \| staged | Launches a specific version of the application. You can specify a version (n), or use keywords like release or staged to launch the latest release or staged vers
needs to be passive voice,

2023-12-04 10:18 UTC, davidmarkclements commented on cli.md
> +Open a Read-Evaluate-Print-Loop (REPL) session with the Sidecar. It prints a command that you can run to open the session
needs to be passive voice

2023-12-06 10:51 UTC, davidmarkclements commented on cli.md
> +{% hint style="info" %}
nice, did not know about this

2023-12-06 10:52 UTC, davidmarkclements commented on cli.md
> +{% hint style="info" %}
however it seems weird to use it here

2023-12-06 10:52 UTC, davidmarkclements commented on cli.md
> +Sets up a Pear project with a initial project files.
"a initial"

2023-12-06 10:53 UTC, davidmarkclements commented on cli.md
> +{% hint style="info" %}
not sure we should do this here, but good to know we can do this

2023-12-06 10:53 UTC, davidmarkclements commented on cli.md
> +| --no-watch         | Turns off the watch-reload feature that refreshes the application automatically when file changes are detected.                         |
much better

2023-12-06 10:53 UTC, davidmarkclements commented on cli.md
> +| --launch=key       | Launches an application in dev mode using its key.                                                                                   |
development mode

2023-12-06 10:54 UTC, davidmarkclements commented on cli.md
> +Stages the application from the filesystem to a P2P data-structure with a given channel name or key. This can be used to continuously deploy a staging preview version of a Pear project. When staging,
```suggestion
Stages the application from the filesystem to a P2P data-structure (Hypercore) with a given channel name or key. This can be used to continuously deploy a staging preview version of a Pear project. When staging, the CLI prints the difference between the current and previous versions, along with the project key.
```

2023-12-06 10:57 UTC, davidmarkclements commented on cli.md
> +For seeding a staged project, specify a staged channel from a project folder. For reseeding, specify the public key of a project.
this isn't quite true 

if I stage a project, I now have a local p2p structure with a key 
I can seed that project with `pear seed <channel>` AND I can seed that project with `pear seed <key>`

If I have the key of another project, I can reseed it with `pear seed <key>`

But you're making a distinction here between staged vs not-staged and channel vs key - that is not the case

2023-12-06 10:59 UTC, davidmarkclements commented on cli.md
> +Seeding in Pear refers to the process of updating Pear project data to or from other P2P data-structures.
incorrect 
 quotes from bittorrent docs:
> Seeding means sharing a file(s) with other peers.  After a torrent job finishes downloading, if you leave the torrent job seeding, it uploads the file(s) to other peers so they can enjoy them too.

reduce the focus on P2P-data structures, talk about peers 
it's not to or from

2023-12-06 11:01 UTC, davidmarkclements commented on cli.md
> +| --checkout=n \| release \| staged | Launches a specific version of the application by specifying a version number or using keywords like 'release' or 'staged' for the latest release or staged versi
confusing the subject of the sentence with "Launches" and "by specifying" - the first is what pear does and the second is what the user does 

"Opens the application at a specified version"

Staged is latest, Release is latest marked release. There are no other keywords.

2023-12-06 11:03 UTC, davidmarkclements commented on cli.md
> +Dumps a Pear project's files from P2P data structures to a local directory using the project's key.
consistency: data-structures

what should the user understand by "using the projects key", what info does that convey that they don't already have?

2023-12-06 11:05 UTC, davidmarkclements requested changes
.

2023-12-06 14:16 UTC, davidmarkclements commented on cli.md
> +Stages the application from the filesystem to a P2P data-structure (Hypercore) with a given channel name or key. This can be used to continuously deploy a staging preview version of a Pear project. W
```suggestion
Stages the application from the filesystem to a P2P data-structure (Hypercore) with a given channel name or key. This can be used to continuously deploy a staging preview version of a Pear project. When staging, the difference between the current and previous versions is output, along with the project key.
```

2023-12-06 14:18 UTC, davidmarkclements commented on cli.md
> +Dumps a Pear project's files from P2P data-structures to a local directory.
what does dump mean.

2023-12-06 14:28 UTC, mafintosh commented on cli.md
> +In the context of Pear, seeding is the act of synchronizing and distributing the project data within the Pear network
Is this chatgpt? Sounds AI’ey

2023-12-06 15:22 UTC, subashsn commented on cli.md
> +In the context of Pear, seeding is the act of synchronizing and distributing the project data within the Pear network
Nope, don't like it? 

Also the word reseed isn't very intuitive to it's function i.e downloading from peers. Can retrieve / sync from peers, etc.

2023-12-06 15:30 UTC, subashsn commented on cli.md
> +Dumps a Pear project's files from P2P data-structures to a local directory.
Made it downloads

2023-12-07 09:13 UTC, subashsn commented on cli.md
> +In the context of Pear, seeding is the act of synchronizing and distributing the project data within the Pear network
@mafintosh Is this better now?

2023-12-07 09:13 UTC, subashsn commented on cli.md
> +Seeding in Pear refers to the process of updating Pear project data to or from other P2P data-structures.
@davidmarkclements Is this better now?

2023-12-07 12:07 UTC, closed without merging