add trust dialog info
holepunchto/pear-docs pull request #102
Opened 2024-04-22 13:17 UTC by heyitsvi

2024-04-22 17:03 UTC, subashsn requested changes

2024-04-22 17:03 UTC, subashsn commented on guide/sharing-a-pear-app.md
> +
Suggest adding a screenshot as example

2024-04-22 17:03 UTC, subashsn commented on guide/sharing-a-pear-app.md
> +> During development with `pear dev`, applications are automatically trusted, as they are assumed to be safe for testing purposes. Trust dialog can be avoided by using the `--no-ask-trust` flag with
This can be below the CLI flow below

2024-04-22 17:03 UTC, subashsn commented on guide/sharing-a-pear-app.md
> +```
You can add a line saying, when starting an application in terminal you get a message, etc..

2024-04-22 17:03 UTC, subashsn commented on guide/sharing-a-pear-app.md
> +If the application is being opened for the first time on the peer it has no state at all, so the application may show a loader until it's ready to reveal.
grammar issue

2024-04-22 17:33 UTC, heyitsvi commented on guide/sharing-a-pear-app.md
> +If the application is being opened for the first time on the peer it has no state at all, so the application may show a loader until it's ready to reveal.
changes as requested, pushed

2024-04-22 19:34 UTC, subashsn commented on assets/image.png:Zone.Identifier
?

2024-04-23 09:38 UTC, subashsn approved these changes

2024-04-23 10:36 UTC, rafapaezbas approved these changes

2024-04-23 10:37 UTC, merged