add missing media access functions
holepunchto/pear-docs pull request #104
Opened 2024-04-26 09:48 UTC by heyitsvi

2024-04-26 10:23 UTC, subashsn requested changes

2024-04-26 10:23 UTC, subashsn commented on reference/pear/api.md
> +The mediaType can have the values `microphone` and `camera`. To leverage this API extra options need to set which can found in references.
@heyitsvi Grammar

2024-04-26 10:23 UTC, subashsn commented on reference/pear/api.md
> +The mediaType can have the values `microphone` and `camera`. To leverage this API extra options need to set which can found in references.
Also no screen here?

2024-04-26 10:26 UTC, heyitsvi commented on reference/pear/api.md
> +The mediaType can have the values `microphone` and `camera`. To leverage this API extra options need to set which can found in references.
Nope only two options, checked it.

2024-04-26 10:57 UTC, subashsn commented on reference/pear/api.md
> +The mediaType can have the values `microphone` and `camera`. To leverage this API extra options need to set which can found in references.
then how does screen share work

2024-04-26 11:58 UTC, heyitsvi commented on reference/pear/api.md
> +The mediaType can have the values `microphone` and `camera`. To leverage this API extra options need to set which can found in references.
https://www.electronjs.org/docs/latest/api/system-preferences#systempreferencesgetmediaaccessstatusmediatype-windows-macos
In the docs screen access is only required for some higher versions of macOS, otherwise granted for both windows and mac
You can see both the functions here, the ask access function explicitly states only two options, the check status has all three though

2024-04-26 12:35 UTC, subashsn commented on reference/pear/api.md
> +The mediaType can have the values `microphone` and `camera`. To leverage this API extra options need to set which can found in references.
Thats fine. Pls find out how screenshare works then on higher versions of mac os? Maybe they didn't add it to the ask in docs? Check electron code,you can raise PR in electron too if so

2024-04-29 11:19 UTC, subashsn requested changes

2024-04-29 11:19 UTC, subashsn commented on reference/pear/api.md
> +* `animate <Boolean>` Default: `false` - animate the dimensional change. macOS only, ignored on other OS's.
on other OS.

2024-04-29 11:19 UTC, subashsn commented on reference/pear/api.md
> +The mediaType can have the values `microphone` and `camera`. To leverage this API extra options need to be set which can be found in references.
the To leverage sentence can have some improvements

2024-04-29 11:48 UTC, heyitsvi commented on reference/pear/api.md
> +The mediaType can have the values `microphone` and `camera`. To leverage this API extra options need to be set which can be found in references.
updated

2024-04-30 09:23 UTC, subashsn approved these changes

2024-04-30 13:37 UTC, rafapaezbas commented on reference/pear/api.md
> +### `const status = await Pear.media.getMediaAccessStatus(mediaType)`
`Pear.media` does not expose `getMediaAccessStatus` or `askForMediaAccess` these are the methods exposed: https://github.com/holepunchto/pear-docs/blob/33dd6e8c8ba6916d83a07e6c1fa188c0ecb19ece/reference/pear/api.md?plain=1#L268-L308

2024-05-01 06:46 UTC, closed without merging