add pear worker
holepunchto/pear-docs pull request #113
Opened 2024-06-10 12:21 UTC by heyitsvi

2024-06-11 12:32 UTC, subashsn requested changes

2024-06-11 12:32 UTC, subashsn commented on reference/pear/configuration.md
> +Mapping of names to Pear application keys.
Grammar

2024-06-11 12:32 UTC, subashsn commented on reference/pear/api.md
> +Spawns a new process by using the specified key as the entry point. Resolves to a `Duplex` stream object representing a pipe.
"by using the" -> "with the"

2024-06-11 12:32 UTC, subashsn commented on reference/pear/api.md
> +Used within the worker process to get the communication pipe which is also returned by the `Pear.worker.run(key <String>)` function. Resolves to a `Duplex` stream object representing a pipe.
Grammar improve

2024-06-11 13:05 UTC, rafapaezbas commented on reference/pear/configuration.md
> +###  `pear.links <Object>`
pear.links can be an object or an array of keys. All the values stored (in the array or the object) are trusted application keys.

2024-06-11 13:08 UTC, rafapaezbas commented on reference/pear/configuration.md
> +Represents the key of the Pear application that contains the worker script.
might be useful to add a reference to the example app https://github.com/holepunchto/pear/blob/main/examples/desktop/app.js#L27 and https://github.com/holepunchto/pear/blob/main/examples/terminal/index.js#L21, or add the minimal example could be nice too.

2024-06-12 08:00 UTC, subashsn approved these changes

2024-06-12 08:27 UTC, rafapaezbas approved these changes

2024-06-12 08:35 UTC, merged