add pear gc
holepunchto/pear-docs pull request #114
Opened 2024-06-11 10:24 UTC by heyitsvi

2024-06-11 12:32 UTC, subashsn requested changes

2024-06-11 12:32 UTC, subashsn commented on reference/pear/cli.md
> +Garbage Collection. Remove unused resources.
Perform Garb... ?

2024-06-12 07:59 UTC, subashsn commented on reference/pear/cli.md
> +Garbage Collection. Remove unused resources.
This doesn't seem to be merged?

2024-06-12 08:34 UTC, rafapaezbas commented on reference/pear/cli.md
> +| release   | Clear inactive releases                       |
changed from `release` to `releases` and `sidecar` to `sidecars` see commit https://github.com/holepunchto/pear/commit/a1f9c423b7f3ef6e8505e369e929973df65f0589

2024-06-12 09:28 UTC, rafapaezbas approved these changes

2024-06-12 09:29 UTC, merged