Add Inspector tab
holepunchto/pear-docs pull request #20
Opened 2024-01-24 13:25 UTC by freeall

Adds inspect feature. Works together with https://github.com/holepunchto/pear/pull/411.

<img width="1090" alt="image" src="https://github.com/holepunchto/pear-pulse/assets/376654/7770b59a-419e-4ab2-bce8-a54faabbb203">

How to test:

1. Use https://github.com/holepunchto/pear/pull/411
2. Create Pear terminal app (`{"pear": {"type": "terminal"}}` in the app's `package.json`)
3. Run the app like `$ pear.dev dev . --inspect`. The app will output a 64-string long key
4. Paste the key into the field in the Inspector tab in Pear Pulse
5. Open `chrome://inspect` and see your app there

2024-01-24 13:34 UTC, rafapaezbas commented on lib/devtools-inspector.js
> +    this.$addKeyForm = this.root.querySelector('#add-key-form')
Seems like we are not using the $name convention, see here https://github.com/holepunchto/pear-pulse/blob/main/lib/docs-viewer.js#L55

2024-01-24 13:43 UTC, rafapaezbas commented on lib/devtools-inspector.js
> +      const key = this.$addKey.value
the error reset should happen on a 'change' event maybe?

2024-01-24 13:50 UTC, rafapaezbas commented on lib/devtools-inspector.js
> +        url: `file:///path/to/some/file/index.js`,
is this a placeholder?

2024-01-24 13:55 UTC, rafapaezbas commented on lib/devtools-inspector.js
> +      const sessionId = request.url.substr(1)
does this remove '/'? is there any chance that its not part of the url?

2024-01-24 13:59 UTC, rafapaezbas commented on lib/devtools-inspector.js
> +    const content = [...this.apps.values()].map(app => `
maybe `this.apps.values().map(app => ....)` works too?

2024-01-26 13:46 UTC, freeall commented on lib/devtools-inspector.js
> +    const content = [...this.apps.values()].map(app => `
Just tried it out, and apparently nope :)

2024-01-26 13:47 UTC, freeall commented on lib/devtools-inspector.js
> +      const sessionId = request.url.substr(1)
Yeah, it just removes that `/`. There shouldn't be any chance that it's not part of the url as it's part of how `chrome://inspect` works.

2024-01-29 13:15 UTC, rafapaezbas commented on lib/devtools-inspector.js
> +      const inspectorSession = new Session({ publicKey: Buffer.from(publicKey, 'hex') })
I think `b4a` its prefered over `Buffer`

2024-01-29 13:19 UTC, rafapaezbas commented on lib/devtools-inspector.js
> +        this.addKeyErrorElem.textContent = ''
should the error reset happen on 'change' instead of submit?

2024-01-30 13:03 UTC, davidmarkclements commented on package.json
> +        "overpass": "github:RedHatOfficial/Overpass#71f18db",
please use https://www.npmjs.com/package/redhat-overpass-font

2024-01-30 13:04 UTC, davidmarkclements commented
landing screen bug 
![image](https://github.com/holepunchto/pear-runtime/assets/1190716/03b05e3a-0444-4569-97e0-1eb0c8b5bfa8)

2024-01-30 13:07 UTC, davidmarkclements requested changes
typo: availble, landing screen bug, replace gh package font with npm package, call the section "Developer Tooling" instead of "Inspector" (inspector is a subsection which happens to be the first, this section will grow as we go)

2024-01-30 21:53 UTC, merged