Update pictures and add config
holepunchto/pear-docs pull request #4
Opened 2023-12-08 14:39 UTC by freeall

2023-12-08 14:45 UTC, davidmarkclements commented
re the combined images, can they be on transparent background 2px gap between

2023-12-08 14:45 UTC, davidmarkclements commented on guide/making-a-pear-app.md
> +To make sure that the app looks the way intended, update the `pear` property in `package.json`. See all the possibly options in the [reference doc](../reference/configuration.md).
nice inter-linking

2023-12-08 14:46 UTC, davidmarkclements commented on guide/starting-a-pear-project.md
> +## Step 4. Chagne gui settings
Change

stick to the same language, it's configuration

2023-12-08 14:46 UTC, davidmarkclements commented on guide/starting-a-pear-project.md
> +## Step 4. Chagne gui settings
GUI

2023-12-08 14:47 UTC, davidmarkclements commented on guide/starting-a-pear-project.md
> +      "alwaysOnTop": true
make sure this works cross-platform before we go with this

2023-12-08 14:48 UTC, davidmarkclements commented on guide/starting-a-pear-project.md
> +      "alwaysOnTop": true
actually, idk this is a cool idea, but this is a first app situation - and alwaysOnTop is non-typical 

so while it is a cool idea, I don't think we should do this here

2023-12-08 14:48 UTC, davidmarkclements commented on guide/starting-a-pear-project.md
> +      "alwaysOnTop": true
width height and bg are fine

2023-12-08 14:49 UTC, davidmarkclements commented on guide/starting-a-pear-project.md
> +It's possible to change various settings with Pear. This is done with the `pear` property in `package.json`. See all the possibly options in the [reference doc](../reference/configuration.md).
link to configuration after the json code

reference doc is too vague: Configuration Documentation

2023-12-08 14:50 UTC, davidmarkclements commented on guide/starting-a-pear-project.md
> +## Step 5. Create a basic UI
avoid using acronyms until after the full form with acronym in brackets is stated: User Interface (UI) needs to be read before UI is read again.

2023-12-08 14:52 UTC, davidmarkclements commented on guide/starting-a-pear-project.md
> +## Step 5. Create a basic UI
do a pass everywhere for this

2023-12-08 14:52 UTC, davidmarkclements requested changes
great so far, few tweaks

2023-12-08 15:18 UTC, freeall commented
@davidmarkclements went over all the comments. Can you take a look again?

2023-12-08 15:20 UTC, davidmarkclements commented on guide/starting-a-pear-project.md
> +- `index.html`. The html for the app.
HTML

but it's the application entry point

consider that we'll be writing analogous articles for terminal applications

2023-12-08 15:24 UTC, davidmarkclements commented on guide/starting-a-pear-project.md
> +## Step 5. Create a basic User Interface (UI)
```suggestion
The next step covers creating a basic User Interface (UI) for the application.

## Step 5. Creating the application UI
```

2023-12-08 15:27 UTC, davidmarkclements commented on guide/making-a-pear-app.md
> +## Step 3. Update Graphical User Interface (GUI) settings
```suggestion
The next step covers how to configure Graphical User Interface (GUI) settings for the application.

## Step 3. GUI Configuration
```

2023-12-08 15:29 UTC, davidmarkclements commented on guide/starting-a-pear-project.md
> +      "alwaysOnTop": true
this step should be removed, only need to intro pear gui in starting

2023-12-11 10:40 UTC, davidmarkclements approved these changes
:+1:

2023-12-11 10:40 UTC, merged