Add bare reference to docs
holepunchto/pear-docs pull request #88
Opened 2024-03-08 15:49 UTC by heyitsvi

Bare Reference section includes :
- Overview
- API
- Node.js Compat
- Bare Module

Updated SUMMARY and README for the same.

2024-03-11 14:10 UTC, subashsn commented on bare-reference/api.md
> +
Add an intro, like this

https://docs.pears.com/pear-runtime/api

2024-03-11 14:14 UTC, subashsn requested changes

2024-03-11 14:14 UTC, subashsn commented on bare-reference/api.md
> +
Add an intro like in Pear API
https://docs.pears.com/pear-runtime/api

2024-03-11 14:14 UTC, subashsn commented on bare-reference/overview.md
> +Find the Bare API specs [here](./api.md).
New line. + Expand a little hire, just a line. on what it allows it you to do

2024-03-12 06:11 UTC, heyitsvi commented on bare-reference/api.md
> +
Done

2024-03-12 06:11 UTC, heyitsvi commented on bare-reference/overview.md
> +Find the Bare API specs [here](./api.md).
Done

2024-03-12 12:19 UTC, subashsn approved these changes

2024-03-12 12:35 UTC, rafapaezbas commented on bare-reference/bare-modules.md
> +##### Subpath imports
Is some explanation missing for Subpath imports, Conditional imports and Private imports?

2024-03-12 12:35 UTC, rafapaezbas commented on bare-reference/bare-modules.md
> +Constant | Description
If description column is empty, we should just remove it.

2024-03-12 12:37 UTC, rafapaezbas commented on bare-reference/bare-modules.md
> +#### `module.url`
Should we add some descriptions for these properties?

2024-03-12 13:23 UTC, heyitsvi commented on bare-reference/bare-modules.md
> +##### Subpath imports
yes it's missing right now, content ref : https://github.com/holepunchto/bare-module

2024-03-12 13:24 UTC, heyitsvi commented on bare-reference/bare-modules.md
> +Constant | Description
We did have a discussion on it, included it for completeness but the entire API section needs to be fleshed out. Should we remove the complete section for now?

2024-03-13 08:20 UTC, merged